apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appconfig-rolebinding
subjects:
- kind: ServiceAccount
  name: appconfig-sa
  namespace: default
roleRef:
  kind: Role
  name: appconfig-crd
  apiGroup: rbac.authorization.k8s.io
